// <auto-generated />
namespace MyEcomDemoShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBaskets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBaskets));
        
        string IMigrationMetadata.Id
        {
            get { return "202103251751177_AddBaskets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
